### Get all attractions
GET http://localhost:8080/attractions
Accept: application/json

###Save Pyramids of Giza
POST http://localhost:8080/attractions/save
Content-Type: application/json

{
  "name": "Pyramids of Giza",
  "description": "The iconic pyramids built as tombs for ancient Pharaohs.",
  "city": "Giza",
  "tags": ["HISTORY", "UNESCO", "MONUMENT"]
}


### Get a specific attraction by name
GET http://localhost:8080/attractions/Pyramids%20of%20Giza
Accept: application/json

### Add luxor temple
POST http://localhost:8080/attractions/save
Content-Type: application/json

{
  "name": "Luxor Temple",
  "description": "A large Ancient Egyptian temple complex located on the east bank of the Nile.",
  "city": "Luxor",
  "tags": ["HISTORY", "TEMPLE", "ANCIENT"]
}

### Update luxor temple
POST http://localhost:8080/attractions/update
Content-Type: application/json

{
  "name": "Luxor Temple",
  "description": "An ancient temple complex in Luxor, dedicated to the Theban Triad.",
  "city": "Luxor",
  "tags": ["HISTORY", "TEMPLE", "ANCIENT", "UNESCO"]
}


### Delete luxor temple
POST http://localhost:8080/attractions/delete/Luxor Temple
Content-Type: application/json
